# Generated by Django 3.1.1 on 2020-09-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('House', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('client_name', models.CharField(max_length=255, verbose_name='client_name')),
                ('client_region', models.CharField(max_length=255, verbose_name='Client_region')),
                ('client_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_address', to='coffe_m.client_address')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manager', to='coffe_m.manager')),
            ],
        ),
    ]
