# Generated by Django 3.1.1 on 2020-09-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_m', '0003_auto_20200908_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_coffemachine',
            name='coffemachines',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coffemachines', to='coffe_m.coffemachine'),
        ),
    ]
