# Generated by Django 3.1.1 on 2020-09-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_m', '0005_auto_20200908_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffemachine',
            name='visits',
        ),
        migrations.AddField(
            model_name='visit',
            name='coffemachine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffemachine', to='coffe_m.coffemachine'),
        ),
    ]
