# Generated by Django 3.1.1 on 2020-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_m', '0007_auto_20200909_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание кода')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Useful_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_machine', models.CharField(max_length=255, verbose_name='Модель кофемашины')),
                ('document', models.CharField(max_length=255, verbose_name='Документация')),
            ],
        ),
    ]
