# Generated by Django 3.1.1 on 2020-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_m', '0008_useful_code_useful_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useful_docs',
            name='document',
            field=models.FileField(max_length=255, upload_to='', verbose_name='Документация'),
        ),
    ]
